// Generated by CoffeeScript 1.4.0
var $b, browser, userdata;

browser = require("browser");

userdata = {
  email: "ygd.weibo.superwolf@gmail.com",
  pass: "superwolf"
};

browser = require("browser");

$b = new browser();

$b.browse('login', 'https:#accounts.google.com/Login', {
  debug: true
});

$b.browse(function(err, out) {
  var $, jquery, jsdom, postdata, url, window;
  jsdom = require("jsdom").jsdom;
  jquery = require("jquery");
  window = jsdom(out.result).createWindow();
  $ = jquery.create(window);
  postdata = {
    Email: userdata.email,
    Passwd: userdata.pass
  };
  url = $("#gaia_loginform").attr("action");
  $("input").each(function(k, el) {
    var $el, name, type, val;
    $el = $(el);
    name = $el.attr("name");
    type = $el.attr("type");
    val = $el.val();
    if (type === "hidden" || type === "submit") {
      return postdata[name] = val;
    }
  });
  return [
    url, {
      data: postdata,
      method: "POST"
    }
  ];
}).after("login");

$b.browse('https:#mail.google.com/mail/u/0/?ui=html&zy=d').after();

$b.on("end", function(err, out) {
  return console.log(out.result);
});

$b.run();
